version: '3'
services:
  portfolio-web:
    build:
      context:  ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - 9999:80
    restart: always
  porrfolio-backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - 9998:9998
    environment:
      - NODE_ENV=production
